### ISSUE TITLE
% Completion not working at all

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#398]

**Comment by ifoche** [comment]
@josemp10 this is already solved isn't it?

**Comment by ifoche** [comment]
@josemp10 are you receiving these notifications?

**Comment by josemp10** [comment]
Yes, sorry for the slow response.

It is NOT solved yet. Anyway this is not a prioratiry now (but a nice to
have), because PSI is going to change the definition of completion rate...
Likely we don't have an answer for this till mid-October...

**Comment by ifoche** [comment]
ok, we'll do this during next week, using the testing and debugging. I'll take care of it

**Comment by josemp10** [comment]
perfect. Anyway, let's have a brief chat next week (10 minutes), so I can
show you what the problem is (just to save your time).

**Comment by ifoche** [comment]
sure!

**Comment by ifoche** [comment]
This has become very important and doesn't only affect to custom tabs, but to every kind of tab. Percentage doesn't correspond to reality. This is not the first time we get here, we need to solve it now and permanently.

**Comment by josemp10** [comment]
I have took a look at the problem with the custom tabs. The logic (SQL
sentence) may need to be a bit different for the custom tabs. Maybe we can
talk tomorrow or on Wednesday (if you want to), so I can show you what the
problem is...

**Comment by ifoche** [comment]
That would be great!

**Comment by ifoche** [comment]
found a very ugly solution. Need to think a little bit more about it
